name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 10.0.2
topics:
  - share
  - utils

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FPPSharePlusPlugin
      linux:
        dartPluginClass: SharePlusLinuxPlugin
      macos:
        pluginClass: SharePlusMacosPlugin
      web:
        pluginClass: SharePlusWebPlugin
        fileName: src/share_plus_web.dart
      windows:
        dartPluginClass: SharePlusWindowsPlugin
        pluginClass: SharePlusWindowsPluginCApi

dependencies:
  cross_file: ^0.3.4+2
  meta: ^1.8.0
  mime: ^1.0.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  share_plus_platform_interface: ^5.0.0
  file: ">=6.1.4 <8.0.0"
  url_launcher_web: ^2.3.2
  url_launcher_windows: ^3.1.2
  url_launcher_linux: ^3.1.1
  url_launcher_platform_interface: ^2.3.2
  ffi: ^2.1.2
  web: ^1.0.0
  plugin_platform_interface: ^2.1.4
  path_provider: ^2.0.14
  uuid: ">=3.0.7 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"
  mockito: ^5.4.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
